# Generated by Django 3.1.2 on 2020-10-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0002_sellandbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellcake',
            name='cake_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
