# Generated by Django 3.1.2 on 2020-10-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeshop', '0004_auto_20201015_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='items',
            field=models.CharField(default='', max_length=30),
        ),
    ]
